version: "3"
services:
  frontend:
    container_name: go-chat-frontend
    build: ./frontend
    ports:
      - 8000:8000
    depends_on:
      - backend

  backend:
    container_name: go-chat-backend
    build: ./backend
    ports:
      - 8080:8080
